2024-12-24 12:04:38,015 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\alexk\PycharmProjects\lessons\logging\test_12_4.py", line 23, in test_run
    self.run2 = Runner( 2)
                ^^^^^^^^^^
  File "C:\Users\alexk\PycharmProjects\lessons\logging\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-12-24 12:04:38,016 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\alexk\PycharmProjects\lessons\logging\test_12_4.py", line 12, in test_walk
    self.run1 = Runner('Runner 1', -5)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexk\PycharmProjects\lessons\logging\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
